### ISSUE TITLE
Add Navigation Controller

### ISSUE THREAD

**Issue by RyokoKato** [RyokoKato/OpenCVSwiftTest#10]
### TODO
- [ ] add navigation controller screens exclude Menu Screen
    - [ ] set screen title to all screen
    - [ ] add back button
- [ ] implement pagination
